export interface Community {
  id: number
  name: string
  city: string
  region: string
  country: string
  description: string
  logoUrl: string
  website: string
  memberCount: number
  meetupCount: number
  organizerNames: string[]
  contactLinks: { type: string; url: string }[]
  isVerified: boolean
  receivesGrants: boolean
}

export const communities: Community[] = [
  {
    id: 1,
    name: "ETH Sapporo House",
    city: "Sapporo",
    region: "Hokkaido",
    country: "Japan",
    description:
      "A grassroots Ethereum group for devs and enthusiasts in northern Japan. Monthly study sessions and coffee meetups.",
    logoUrl: "https://placehold.co/80x80/primary/white?text=Sapporo",
    website: "https://geodework.com",
    memberCount: 48,
    meetupCount: 9,
    organizerNames: ["Haruka Ito"],
    contactLinks: [{ type: "Twitter", url: "https://x.com/Geodework" }],
    isVerified: true,
    receivesGrants: false,
  },
  {
    id: 2,
    name: "ETH Brno Craft",
    city: "Brno",
    region: "South Moravia",
    country: "Czech Republic",
    description:
      "Ethereum tinkerers and builders in Brno. We host casual pub nights and hands-on workshops.",
    logoUrl: "https://placehold.co/80x80/primary/white?text=Brno",
    website: "https://geodework.com",
    memberCount: 32,
    meetupCount: 6,
    organizerNames: ["Petr Novak", "Jana Vesela"],
    contactLinks: [{ type: "Telegram", url: "https://x.com/Geodework" }],
    isVerified: true,
    receivesGrants: true,
  },
  {
    id: 3,
    name: "ETH Rosario",
    city: "Rosario",
    region: "Santa Fe",
    country: "Argentina",
    description:
      "A friendly local group for Ethereum fans in Rosario. We meet for mate, code, and community updates.",
    logoUrl: "https://placehold.co/80x80/primary/white?text=Rosario",
    website: "https://geodework.com",
    memberCount: 21,
    meetupCount: 4,
    organizerNames: ["Lucia Fernandez"],
    contactLinks: [
      { type: "Twitter", url: "https://x.com/Geodework" },
      { type: "Email", url: "https://x.com/Geodework" },
    ],
    isVerified: false,
    receivesGrants: false,
  },
  {
    id: 4,
    name: "Uzumaki House",
    city: "Osaka",
    region: "Kansai",
    country: "Japan",
    description:
      "A cozy crypto co-living and event space. Weekly Ethereum and DeFi chats, open to all.",
    logoUrl: "https://placehold.co/80x80/primary/white?text=Uzumaki",
    website: "https://geodework.com",
    memberCount: 17,
    meetupCount: 12,
    organizerNames: ["Kenji Sato"],
    contactLinks: [{ type: "Instagram", url: "https://x.com/Geodework" }],
    isVerified: true,
    receivesGrants: false,
  },
  {
    id: 5,
    name: "Centrum Crypto",
    city: "Poznań",
    region: "Greater Poland",
    country: "Poland",
    description:
      "A local hub for blockchain and Ethereum meetups, workshops, and hack nights.",
    logoUrl: "https://placehold.co/80x80/primary/white?text=Centrum",
    website: "https://geodework.com",
    memberCount: 28,
    meetupCount: 7,
    organizerNames: ["Marta Kowalska"],
    contactLinks: [{ type: "Twitter", url: "https://x.com/Geodework" }],
    isVerified: true,
    receivesGrants: true,
  },
  {
    id: 6,
    name: "LatinCrypt",
    city: "Medellín",
    region: "Antioquia",
    country: "Colombia",
    description:
      "Latin American crypto podcast community. Hosts monthly Ethereum meetups and AMAs.",
    logoUrl: "https://placehold.co/80x80/primary/white?text=LatinCrypt",
    website: "https://geodework.com",
    memberCount: 54,
    meetupCount: 10,
    organizerNames: ["Carlos Rojas", "Ana María López"],
    contactLinks: [
      { type: "Twitter", url: "https://x.com/Geodework" },
      { type: "Podcast", url: "https://x.com/Geodework" },
    ],
    isVerified: true,
    receivesGrants: true,
  },
  {
    id: 7,
    name: "CryptoCafé",
    city: "Lisbon",
    region: "Lisbon",
    country: "Portugal",
    description:
      "A casual Ethereum and crypto discussion group meeting in local cafés.",
    logoUrl: "https://placehold.co/80x80/primary/white?text=CryptoCafé",
    website: "https://geodework.com",
    memberCount: 19,
    meetupCount: 5,
    organizerNames: ["João Silva"],
    contactLinks: [{ type: "Telegram", url: "https://x.com/Geodework" }],
    isVerified: true,
    receivesGrants: false,
  },
  {
    id: 8,
    name: "ETH Tbilisi",
    city: "Tbilisi",
    region: "Tbilisi",
    country: "Georgia",
    description:
      "Ethereum builders and learners in Georgia. We host code jams and pizza nights.",
    logoUrl: "https://placehold.co/80x80/primary/white?text=Tbilisi",
    website: "https://geodework.com",
    memberCount: 23,
    meetupCount: 6,
    organizerNames: ["Nino Beridze"],
    contactLinks: [{ type: "Twitter", url: "https://x.com/Geodework" }],
    isVerified: true,
    receivesGrants: false,
  },
  {
    id: 9,
    name: "ETH Cape Town",
    city: "Cape Town",
    region: "Western Cape",
    country: "South Africa",
    description:
      "A small but passionate group of Ethereum enthusiasts. Monthly meetups at local tech hubs.",
    logoUrl: "https://placehold.co/80x80/primary/white?text=CapeTown",
    website: "https://geodework.com",
    memberCount: 27,
    meetupCount: 8,
    organizerNames: ["Sipho Dlamini"],
    contactLinks: [{ type: "Twitter", url: "https://x.com/Geodework" }],
    isVerified: true,
    receivesGrants: false,
  },
  {
    id: 10,
    name: "ETH Manila",
    city: "Manila",
    region: "Metro Manila",
    country: "Philippines",
    description:
      "Ethereum and DeFi fans in Manila. We host workshops and social nights for all levels.",
    logoUrl: "https://placehold.co/80x80/primary/white?text=Manila",
    website: "https://geodework.com",
    memberCount: 36,
    meetupCount: 11,
    organizerNames: ["Miguel Santos"],
    contactLinks: [{ type: "Facebook", url: "https://x.com/Geodework" }],
    isVerified: true,
    receivesGrants: false,
  },
  {
    id: 11,
    name: "ETH Halifax",
    city: "Halifax",
    region: "Nova Scotia",
    country: "Canada",
    description:
      "A friendly group for Ethereum and blockchain discussions in Atlantic Canada.",
    logoUrl: "https://placehold.co/80x80/primary/white?text=Halifax",
    website: "https://geodework.com",
    memberCount: 14,
    meetupCount: 3,
    organizerNames: ["Emily Chen"],
    contactLinks: [{ type: "Twitter", url: "https://x.com/Geodework" }],
    isVerified: true,
    receivesGrants: false,
  },
  {
    id: 12,
    name: "Crypto Chai",
    city: "Ahmedabad",
    region: "Gujarat",
    country: "India",
    description:
      "Crypto Chai is a podcast and local meetup for Ethereum and Web3 in Gujarat.",
    logoUrl: "https://placehold.co/80x80/primary/white?text=Chai",
    website: "https://geodework.com",
    memberCount: 22,
    meetupCount: 7,
    organizerNames: ["Ravi Patel"],
    contactLinks: [
      { type: "Podcast", url: "https://x.com/Geodework" },
      { type: "Twitter", url: "https://x.com/Geodework" },
    ],
    isVerified: true,
    receivesGrants: false,
  },
  {
    id: 13,
    name: "ETH Graz",
    city: "Graz",
    region: "Styria",
    country: "Austria",
    description:
      "A small group of Ethereum devs and researchers. We meet for code reviews and coffee.",
    logoUrl: "https://placehold.co/80x80/primary/white?text=Graz",
    website: "https://geodework.com",
    memberCount: 11,
    meetupCount: 2,
    organizerNames: ["Stefan Hofer"],
    contactLinks: [{ type: "Twitter", url: "https://x.com/Geodework" }],
    isVerified: true,
    receivesGrants: false,
  },
  {
    id: 14,
    name: "ETH Sofia",
    city: "Sofia",
    region: "Sofia City",
    country: "Bulgaria",
    description:
      "Ethereum and blockchain enthusiasts in Sofia. We host monthly meetups and talks.",
    logoUrl: "https://placehold.co/80x80/primary/white?text=Sofia",
    website: "https://geodework.com",
    memberCount: 25,
    meetupCount: 5,
    organizerNames: ["Viktor Dimitrov"],
    contactLinks: [{ type: "Telegram", url: "https://x.com/Geodework" }],
    isVerified: true,
    receivesGrants: false,
  },
  {
    id: 15,
    name: "ETH Recife",
    city: "Recife",
    region: "Pernambuco",
    country: "Brazil",
    description:
      "A local group for Ethereum and smart contract devs in northeast Brazil.",
    logoUrl: "https://placehold.co/80x80/primary/white?text=Recife",
    website: "https://geodework.com",
    memberCount: 18,
    meetupCount: 4,
    organizerNames: ["Lucas Oliveira"],
    contactLinks: [{ type: "Twitter", url: "https://x.com/Geodework" }],
    isVerified: true,
    receivesGrants: false,
  },
  {
    id: 16,
    name: "ETH Galway",
    city: "Galway",
    region: "Connacht",
    country: "Ireland",
    description:
      "A small, friendly group for Ethereum and DeFi discussions in the west of Ireland.",
    logoUrl: "https://placehold.co/80x80/primary/white?text=Galway",
    website: "https://geodework.com",
    memberCount: 13,
    meetupCount: 3,
    organizerNames: ["Aoife Murphy"],
    contactLinks: [{ type: "Twitter", url: "https://x.com/Geodework" }],
    isVerified: true,
    receivesGrants: false,
  },
  {
    id: 17,
    name: "ETH Boulder",
    city: "Boulder",
    region: "Colorado",
    country: "USA",
    description:
      "Ethereum and Web3 builders in Boulder. We host monthly hack nights and socials.",
    logoUrl: "https://placehold.co/80x80/primary/white?text=Boulder",
    website: "https://geodework.com",
    memberCount: 29,
    meetupCount: 8,
    organizerNames: ["Sarah Lee"],
    contactLinks: [{ type: "Twitter", url: "https://x.com/Geodework" }],
    isVerified: true,
    receivesGrants: false,
  },
  {
    id: 18,
    name: "ETH Cebu",
    city: "Cebu",
    region: "Central Visayas",
    country: "Philippines",
    description: "A local group for Ethereum and blockchain education in Cebu.",
    logoUrl: "https://placehold.co/80x80/primary/white?text=Cebu",
    website: "https://geodework.com",
    memberCount: 16,
    meetupCount: 4,
    organizerNames: ["Janine Reyes"],
    contactLinks: [{ type: "Facebook", url: "https://x.com/Geodework" }],
    isVerified: true,
    receivesGrants: false,
  },
  {
    id: 19,
    name: "ETH Vilnius",
    city: "Vilnius",
    region: "Vilnius County",
    country: "Lithuania",
    description:
      "Ethereum and crypto enthusiasts in Vilnius. We meet for talks and networking.",
    logoUrl: "https://placehold.co/80x80/primary/white?text=Vilnius",
    website: "https://geodework.com",
    memberCount: 20,
    meetupCount: 5,
    organizerNames: ["Dovydas Petrauskas"],
    contactLinks: [{ type: "Telegram", url: "https://x.com/Geodework" }],
    isVerified: true,
    receivesGrants: false,
  },
  {
    id: 20,
    name: "BlockTalks Meetup",
    city: "Auckland",
    region: "Auckland",
    country: "New Zealand",
    description:
      "Monthly Ethereum and crypto meetups hosted by the BlockTalks podcast team.",
    logoUrl: "https://placehold.co/80x80/primary/white?text=BlockTalks",
    website: "https://geodework.com",
    memberCount: 31,
    meetupCount: 9,
    organizerNames: ["Tom Wilson", "Priya Patel"],
    contactLinks: [
      { type: "Podcast", url: "https://x.com/Geodework" },
      { type: "Twitter", url: "https://x.com/Geodework" },
    ],
    isVerified: true,
    receivesGrants: false,
  },
]
